### ISSUE TITLE
What should be response from site if unknown alarm requested

### ISSUE THREAD

**Issue by daniyalyasin93** [rsmp-nordic/rsmp_core#104]
Hello

With 3.1.5, we can request alarms using the request specialization of the alarm messages. How should the site respond if the alarm code id or the component Id is unknown to it?

This behavior is already defined for status messages that they respond with q = unknown or undefined. But how should the same behavior be for alarms?

**Comment by daniyalyasin93** [comment]
@otterdahl

**Comment by otterdahl** [comment]
Hi,

You’re right. This behaviour is not clearly defined in the spec. Perhaps the alarm message could include a ”quality” field, just like status messages in future versions.

While using version 3.1.5 or 3.2, I think the site should reply with a NotAcknowledged message.

**Comment by daniyalyasin93** [comment]
Thank you for the clarification
