### ISSUE TITLE
Site id spoofing?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#11]
Suppose a site A is connected to a supervisor. If a second site B sends messages to the supervisor, using the same site id as A, what should happen?

It seems site B can pretend to be site A just by knowning the site id. Is this correct? Or is the  supervisor supposed to validate site communication based on the IP address it arrives from?

Or is this a case that should be handled by secure socket layer / certificates?

**Comment by otterdahl** [comment]
Validating based on IP address is one way of doing it. It would reduce the risk of entering the wrong siteId by mistake. The supervisor has the ability to deny communication if there is a mismatch on the expected sideId during RSMP/SXL version message exchange. In our system we have the ability to block the individual IP address of the controller to prevent if from continously trying to reconnect.

**Comment by emiltin** [comment]
Recommendation is to run RSMP on a secure line. There are no current plans to add keys, encryption, etc in RSMP itself.
