### ISSUE TITLE
online documentation gives 404 error

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_core#111]
All links from this site: https://rsmp-nordic.org/specification/ to the documentation, gives 404 errors.

**Comment by otterdahl** [comment]
Also discussed here: https://github.com/rsmp-nordic/rsmp_website/pull/38

**Comment by emiltin** [comment]
closing in favour if the existing isssue #38. thanks for reporting this.
as a temporary solution we're using the raw github.io urls.
