### ISSUE TITLE
aSp should be Resume in alarm resume response, not Suspend?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#112]
In the core spec at https://rsmp-nordic.github.io/rsmp_specifications/core/3.2/applicability/basic_structure.html#structure-for-alarm-suspend-message

 
JSon code 10: Response of a resume message:

```json
{
     "mType": "rSMsg",
     "type": "Alarm",
     "mId": "3313526e-b744-434a-b4dd-0cfa956512e0",
     "ntsOId": "",
     "xNId": "",
     "cId": "AB+84001=860VA001",
     "aCId": "A0004",
     "xACId": "",
     "xNACId": "",
     "aSp": "Suspend",
     "ack": "Acknowledged",
     "aS": "Active",
     "sS": "notSuspended",
     "aTs": "2015-05-29T08:58:28.166Z",
     "cat": "D",
     "pri": "3",
     "rvs": [
         {
             "n": "Temp",
             "v": "-18.5"
         }
     ]
}
```

Is it correct that aSp is set to Suspend? Shouldn't it be  set to Resume?

**Comment by otterdahl** [comment]
> Is it correct that aSp is set to Suspend? Shouldn't it be set to Resume?

It is correct according to RSMP. See [table 4.5.](https://rsmp-nordic.github.io/rsmp_specifications/core/3.2.1/applicability/basic_structure.html#id22).

"aSp" is used to determine what type of alarm message it is.

From the TLC, It can be either:
* Issue - an alarm becomes active or inactive
* Acknowledge - an alarm becomes acknowledged
* Suspend - an alarm becomes suspended orresumed

From the supervision system. It can be either:
* Request - request the current state of the alarm
* Acknowledge - acknowledge the alarm
* Suspend - suspend the alarm
* Resume - resume the alarm

When looking at the response from the TLC, one needs to check alarm state which is defined by "ack", "aS" and "sS". In the example above we can se that "sS": "notSuspended".

I guess I can be a bit confusing that "aSp" used in slightly different way depending if it sent by the TLC or the supervision system. From the TLC is tells us what kind of alarm update it is, but from the supervision system it is more of what kind of alarm request it is.

**Comment by emiltin** [comment]
Ok, closing this.
But I think it's rather confusing and I hope we can streamline these kinds of thing in a future version of the spec.
