### ISSUE TITLE
Description of SXL implies excel docs?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#113]
The core spec has a section on SXL:
https://rsmp-nordic.github.io/rsmp_specifications/core/3.2/applicability/sxl.html#structure

This seems to implicitly expect the SXL to be defined as a word or excel document. Since we're now using YAML, this seems inconsistent.

**Comment by emiltin** [comment]
Same with https://rsmp-nordic.github.io/rsmp_specifications/core/3.2/applicability/sxl.html#revision-of-sxl, it mentions "the front page of each SXL"

**Comment by otterdahl** [comment]
Yes, that section was written a long time ago and needs a complete overhaul.

**Comment by otterdahl** [comment]
I've opened a PR here: https://github.com/rsmp-nordic/rsmp_core/pull/138

**Comment by otterdahl** [comment]
Chaning the milestone to 3.2.2 since the PR is almost finished and there is no changes to the protocol

**Comment by otterdahl** [comment]
The PR has been merged. Feel free to review in the draft version [available here](https://rsmp-nordic.github.io/rsmp_specifications/core/3.2.2/applicability/sxl.html).

**Comment by otterdahl** [comment]
The new PR #159 has been merged
