### ISSUE TITLE
Alarm acknowledgement flow?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#117]
Reading the core spec, I have a hard time understanding how acknowledgement of alarms is expected to work:

https://rsmp-nordic.github.io/rsmp_specifications/core/3.2/applicability/basic_structure.html#message-exchange-between-site-and-supervision-system

There are two diagrams:
- An alarm is acknowledged at the supervision system
- An alarm is acknowledged at the site

How can an alarm be acknowledged at the site? Is that manual operation on street?

In this section:
https://rsmp-nordic.github.io/rsmp_specifications/core/3.2/applicability/basic_structure.html#structure-for-alarm-acknowledgement-message

two messages are shown:

- An alarm acknowledgement message
- An alarm acknowledgement response message

But I don't see an alarm acknowledgement response message in any of the flow diagrams?

When a supervisor want to acknowledge an alarm, it sends an alarm acknowledgement message. Is the site supposed to respond with just an alarm acknowledgement response message, or should it also send an alarm issue?

**Comment by otterdahl** [comment]
> How can an alarm be acknowledged at the site? Is that manual operation on street?

Exactly. It is possible for the equipment to send acknowledgments in case this is possible in the operator panel or web interface.

> In this section: https://rsmp-nordic.github.io/rsmp_specifications/core/3.2/applicability/basic_structure.html#structure-for-alarm-acknowledgement-message
> 
> two messages are shown:
> 
> * An alarm acknowledgement message
> * An alarm acknowledgement response message
> 
> But I don't see an alarm acknowledgement response message in any of the flow diagrams?

An alarm acknowledgement response message is essentially the same as an ordinary alarm issue message, but with `aSp=Acknowledge` instead of `Issue`. And with the updated alarm status (`ack=Acknowledged`)

**Comment by emiltin** [comment]
but how should the site responds?
1) alarm acknowledgement response message
2) alarm acknowledgement response message + alarm issue

**Comment by otterdahl** [comment]
1 is correct
