### ISSUE TITLE
How are alarms differentiated, within the same code/component-id?

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_core#119]
For example, A0001, Serious hardware error. What should be sent if there are several serious hardware errors on the device?

Should we just send out several A0001 alarms, with a distinct "description" field?

As an example, lets say there are 3 active A0001 alarms (lamp error, card error, voltage error).

- We send out 3 separate alarm issues. All 3 have A0001 set in the "aCId" field. The "xACId" field would be different, detailing what each error is.

Now what happens when an Acknowledge (or suspend/resume/request) is sent from the instation? Should we reply with 3 separate alarms?

This further begs the question, what to do with the "aS" field? (active/inactive). If there are multiple events associated with an alarm, what does the "aS" field mean then? Is it active when there is at least one event associated with it?

**Comment by emiltin** [comment]
Feel free to reopen if there are follow up questions.
