### ISSUE TITLE
mId (GUID) value update when resending unacked packets

### ISSUE THREAD

**Issue by marcgarba** [rsmp-nordic/rsmp_core#124]
Each time a packet is unacked and is resended to retry, a new message identity "mId" (GUID) value should be generated.
When an ack message arrives, it allows to know exactly which sended packet it corresponds to (how many try was necessary, or just first one delayed?).

Actually the RSMPGS2 simulator sends back the same packet without updating the mId tag.

Perhaps it could be precised in the RSMP core specifications.

**Comment by otterdahl** [comment]
True. The RSMP simulator will try to resend the message if no ack is recieved within a predefined time.

However, this behaviour is not specified in RSMP core. According to the specification, if no message ack is received it is considered a communication disruption which will cause the equipment to disconnect and reconnect.

**Comment by otterdahl** [comment]
Correct. I think it is a good idea to clarify this.

**Comment by otterdahl** [comment]
I opened a PR for this https://github.com/rsmp-nordic/rsmp_core/pull/134

**Comment by otterdahl** [comment]
The PR has been merged into 3.2.2 draft. Closing this
