### ISSUE TITLE
Clarify that command needs all arguments

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#127]
Clarify that commands needs all arguments to be valid, otherwise it results in MessageNotAck. This is only described in the "Error handling" section.

Status, on the other hand, doesn't need to include all values. A supervision system can choose to only request some parts.

**Comment by otterdahl** [comment]
PR in https://github.com/rsmp-nordic/rsmp_core/pull/137

**Comment by emiltin** [comment]
Another approach would be to allow optional attributes, see #148.

**Comment by otterdahl** [comment]
The PR has been merged
