### ISSUE TITLE
Clarify 4.5.3. Unimplemented statuses or commands

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#129]
This sentence can be written more clearly:

> If a status (sCI) or command (cCI) is unimplemented, the site answers with CommandResponse/Response where q or age is set according to the table below. v should be set to null.

**Comment by marcgarba** [comment]
To understand better the subtlety compared with the other case of "unknown" status/command (SXL mismatch),
we could have this written instead :

> _If a status (sCI) or command (cCI) is recognized in relation to its SXL but not implemented the site answers with **StatusResponseOrUpdate/CommandResponse** where q or age is set according to the table below. v should be set to null._

For the 4.5.1 (unknown component object), we could have the same list "StatusResponseOrUpdate/CommandResponse" to be consistent.

**Comment by otterdahl** [comment]
Opened a PR here: https://github.com/rsmp-nordic/rsmp_core/pull/136

**Comment by otterdahl** [comment]
The PR has been merged. Closing this issue
