### ISSUE TITLE
Allow optional command attributes

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#148]
One example:
In case we want to retire security codes in the TLC SXL, we would make the attributes optional, to make the transition easier.

**Comment by emiltin** [comment]
Note: for statuses you choose which attributes you want.

**Comment by marcgarba** [comment]
Yes, for some attributes in commands sometimes also, it could be very interesting to be able to set some as "optional" !
For the "incomplete commands" error, it would just means that only "required" ones are missing (could also concern some optional ones if required in the context. depending of explanations in the SXL).

**Comment by emiltin** [comment]
Right. The most straightforward is the ability to mark each attribute as optional.

This would not cover cases where certain combinations are allowed. To handle that we would need a json schema or similar systems, but for now I think that might be overkill.

**Comment by emiltin** [comment]
To be backward compatible, the core spec should state that attributes are required unless otherwise stated.

**Comment by emiltin** [comment]
Once this change is implemented in core, we should go through the TLC SXL as mark relevant attributes as optional.

**Comment by emiltin** [comment]
Task for the core WG:
Describe in the core spec that command attributes can be marked as optional in SXLs.

**Comment by otterdahl** [comment]
PR: https://github.com/rsmp-nordic/rsmp_core/pull/181

**Comment by emiltin** [comment]
Follow up tasks
- ability to mark command request arguments as optional in SXL yaml sources (schema repo)
- consider optional flag when we generate json schema and validate
- show optional flag in documentation
- go through the TLC sxl and mark relevant arguments as optional
