### ISSUE TITLE
Disallow multiple cCI in a single command request

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#169]
Currently the RSMP spec allows a command request to contain multiple commands (different cCI at the same time), at least it's not specifically disallowed.

However, this is not recommended. It is hard to determine whether one or all command has been successful or not and to which cCI a potential MessageNotAck refers to.

I have not seen anyone actually tried to send a command request with different cCI’s included, but I think it is a good idea to explicitly disallow this due to the many problems it would impose.

**Comment by emiltin** [comment]
Needs some updates to tools.

**Comment by otterdahl** [comment]
PR: https://github.com/rsmp-nordic/rsmp_core/pull/180

**Comment by emiltin** [comment]
Would this include CommandRequests? Would the rvs only be allowed to items with the same cCI?

**Comment by otterdahl** [comment]
> Would this include CommandRequests? Would the rvs only be allowed to items with the same cCI?

Yes. This means that you cannot mix different cCI in the same CommandRequest.
