### ISSUE TITLE
Repeating alarms

### ISSUE THREAD

**Issue by MarcoRijshouwer** [rsmp-nordic/rsmp_core#18]
Dynniq TLCs repeat alarm messages very often. For example, when a TLC detects a lamp error it sends an error every time is tries to switch on that lamp. This results in the same alarm every minute and the operator of the central system gets message every minute.
Is is allowed to repeat alarm messages?

I also see the alarm is often cancelled. Probably because the lamp is switched off. Should a TLC cancel an lamp errors while the error is not fixed?

**Comment by otterdahl** [comment]
I believe this issue has been prematurely moved to review.

Anyway I've made a suggestion 05c52ba10e85657c896dff4e8f1cb600a8030a81 of clarification of the possible alarm states which is used in RSMP.

The possible alarm state transitions are defined in the figure below. 

![alarm_transitions](https://user-images.githubusercontent.com/2820709/84242770-95841600-ab01-11ea-9074-e256884d8652.png)
Alarms should not be sent unless:

- Alarms are unblocked and it’s state changes
- Alarms are sent as part of Communication establishment between sites and supervision system
- Alarms are explicitly requested using Structure for alarm request message

**Comment by otterdahl** [comment]
The figure is based of figure 4.7.2 of Trafikverket TDOK 2019:0313, which is a general document of how alarms and events should be handled for all road side equipment at Trafikverket

**Comment by otterdahl** [comment]
The figure is generated using GraphWiz using a human readable text file

**Comment by otterdahl** [comment]
Added in 3.1.5
