### ISSUE TITLE
Ability for sites to connect to multiple supervisors

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#19]
The spec contains something about how to connect two sites, but nothing about connecting a site to multiple supervisors.

**Comment by emiltin** [comment]
The Ruby rsmp gem supports connecting to any number of supervisors. This could be used for experimenting, if we want to explore specific scenarios or issues.

**Comment by otterdahl** [comment]
I agree that this would be useful.

We've seen several use cases where could be used, e.g. connecting to a supervision system (for monitoring alarms) and at the same time connecting to a bus-priority system and/or to send SPaT data.

**Comment by emiltin** [comment]
In Copenhagen we have a need for connecting TLCs to both RSM and MobiMaestro monitoring systems.

**Comment by emiltin** [comment]
In case this is/becomes a requirement, we should add relevant tests in the rsmp_validator.

**Comment by emiltin** [comment]
# Proposal
An RSMP site (e.g. equipment) must be able to connect to multiple supervisor, and handle concurrent communication with all of them.

For example, a traffic light controller might connect to both a traffic management system and a bus priority system. Or it might connect to both a traffic management system and a secondary monitoring system.

It must be possible to configure the list of supervisor as part of the rsmp configaration. In the configuration, supervisors are identified by their ip addresses.

It must be possible to configure supervisors as read-only. A read-only supervisor is now allowed to commands, but can only request or subscribe to status.

A command request from a read-only supervisor must be rejected with a NotAcknowledged message with reason set to "Command request rejected because supervisor is configured as read-only".

Each supervisor connection is handled separately. When a supervisor sends a command or status request, the response is send only to that particular supervisor.

The site must handle all types of message from all supervisors, including command request, status request and status subscriptions. Commands from multiple supervisor are served on a first-come basis, without any concept of priority.

**Comment by emiltin** [comment]
This would unfortunately be complicated to test with the RSMP Validator. Every test might potentially behave differently if you have other supervisor connected at the same time.

An alternative approach would be to not required sites to handle multiple supervisors, but instead develop a middle-layer that can distribute rsmp message to/from multiple supervisor. It could then be inserted server-side between supervisor systems and sites (equipment).

**Comment by emiltin** [comment]
Many TLC can already connect to several supervisor systems, just not via RSMP. For example, MobiMaestro via RSMP and RMS via a proprietary protocol.

**Comment by otterdahl** [comment]
A suggestion has been added to the draft﻿

**Comment by emiltin** [comment]
alarms should only go to one supervisor, and it should be configurable which one, e.g. 'primary'

**Comment by otterdahl** [comment]
I'm closing this. Feel free to open this issue again if you have any feedback on the draft

**Comment by otterdahl** [comment]
This requirement is relevant traffic signals, but might be unnecessary for other types of equipment. Can we set this at optional, just like e.g. encryption?

**Comment by emiltin** [comment]
ok we'll make it optional, but add that the sxl can require it. the tlc sxl will require it.
