### ISSUE TITLE
Ability to request status of alarms and aggregated status

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#22]
Sometimes the supervision system looses track of the most recent status of alarms and aggregated status.

There should be a possiblity to request the status of alarms and aggregated status.

**Comment by emiltin** [comment]
An option would be to allow a minimum update interval for alarms and aggregated status, eg. 60 seconds. Aggregated status would then be send at least once every 60 sec, even if there are no changes.

**Comment by otterdahl** [comment]
Suggestion added with 7b8aa8209b71131b59b9c00fd559691d923cd859

**Comment by otterdahl** [comment]
Added in 3.1.5
