### ISSUE TITLE
Alarm code format is inconsistent with traffic light SXL

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#29]
The section https://github.com/rsmp-nordic/rsmp_core/blob/master/rst/rsmp.rst#alarm-messages says this about aCId in Alarm messages:

> Alarm suffix with in combination with the component id identifies an alarm. The examples in this document are defined according to the following format: Ayyy, where yyy is a unique number.

But the traffic light SXL uses alarm codes in the format Ayyyy, ie. four digits instead of three.

I think we should either make the examples consistent with the traffic light SXL, or more clearly write that there is no formal requirements, it's just a string.

**Comment by emiltin** [comment]
If any string can be used, the SXL could use more meaningful codes like 'serious_hardware_error', or if space is an issue, just '1', instead of 'A0001'

**Comment by otterdahl** [comment]
I've updated the specification in commit 4f0aaccef318c46dcb2b1d85221b4c8c8c366475

**Comment by emiltin** [comment]
Nice
