### ISSUE TITLE
When can the supervisor send commands/requests?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#34]
The connection sequence is described in https://github.com/rsmp-nordic/rsmp_core/blob/master/rst/rsmp.rst#communication-establishment-between-sites-and-supervision-system.

However, it's not clear to me how soon the supervisor is allowed to send e.g a command request. Can it send it right after the initial watchdog, or must it wait until the site has send aggregated status, alarms or buffered messages?

**Comment by otterdahl** [comment]
I think it can send it right after the initial watchdog. There is no way for the supervisor to be know when it has recieved all alarms or buffered messages from the site.

**Comment by emiltin** [comment]
Yes that makes sense. Should be clarified in the spec.

**Comment by otterdahl** [comment]
The draft has been updated

**Comment by otterdahl** [comment]
I'm closing this. Feel free to open this issue again if you have any feedback on the draft
