### ISSUE TITLE
Case sensitive or not?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#35]
Section https://github.com/rsmp-nordic/rsmp_core/blob/master/rst/rsmp.rst#basic-structure states:

> Parsing is recommended to be performed case insensitive

I think this is too weak. We should be clear about whether parsing should be case sensitive or insensitive. Errors can arise if systems don't agree.

It's also not clear to me whether this means you're allowed to send commands with different casing. Is 'status', 'Status', and 'STATUS' all allowed? I don't think they should be, I think we should enforce a specific casing.

Unfortunately, casing does not currently seem very consistent, e.g. look at these fields from the example at https://github.com/rsmp-nordic/rsmp_core/blob/master/rst/rsmp.rst#message-structure:

```
    "mType": "rSMsg",
    "aSp": "Issue",
    "ack": "notAcknowledged",
    "aS": "active",
    "xACId": "Serious lamp error",
    "cat": "D",
```

It's a rather confusing combination of casing and spacing.

**Comment by emiltin** [comment]
flag for 3.1.6?

**Comment by otterdahl** [comment]
Yes. I think so

**Comment by otterdahl** [comment]
We're changing this to case sensitive.

**Comment by otterdahl** [comment]
I'm closing this. Feel free to open this issue again if you have any feedback on the draft
