### ISSUE TITLE
How to reject RSMP version?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#38]
When connecting, the site sends a Version message with the RSMP versions if can use. If the supervisor cannot accept any of these, how the supervisor should act is perhaps not entirely clear.

Should it:
a) respond with a MessageNotAck, using the rea attribute to explain that RSMP version did not match.
b) respons with a Version message with only the RSMP version the supervisor understand (after which it is expected that the site will return a MessageNotAck).

I'm strongly in favor of ~~b~~ a, and clarifying this as required behaviour in the spec.

**Comment by otterdahl** [comment]
I agree. b) is the best option since it reveals the supported RSMP versions of the supervisor, which simplifies debugging.

The connection sequence needs be updated to this:
![establish-site-system](https://user-images.githubusercontent.com/2820709/70394963-7691b380-19fa-11ea-809c-7db0b3df9284.png)

and for site-site:

![establish-site-site](https://user-images.githubusercontent.com/2820709/70394967-814c4880-19fa-11ea-8090-022cb8183553.png)

**Comment by emiltin** [comment]
Ups sorry, I actually mean i'm in favour af a, because it's simpler, you reject the first version as soon as you see something is wrong. The reason for rejecting and the version that the supervisor do support can be added to the 'rea' attribute of the MessageNotAcknowledged, eg:

```
{"mType":"rSMsg","type":"MessageNotAck","rea":"RSMP versions [3.1.5] requested, but only [3.1.1,3.1.2,3.1.3,3.1.4] supported.","oMId":"324b55cc-77df-491a-a344-08af0f5f3949"}
```

**Comment by otterdahl** [comment]
Yes, but then the contens of 'rea' needs to be specified more strictly in order to make sure that it contains the needed information for debugging. Currently the 'rea' is just a text field without any strict formatting. Using the Version message for this purpose we can keep the current format.

**Comment by emiltin** [comment]
if the supervisor responds the versions it support (knowing there is no rsmp version that both sides support), should it then expect the site to respond with a NotAck - without any 'rea'? If the site  just goes on, this surely cannot be acceptable.

**Comment by emiltin** [comment]
Or should the supervisor close the connection after sending it's version?

**Comment by otterdahl** [comment]
According to the [specification](https://github.com/rsmp-nordic/rsmp_core/blob/master/rst/rsmp.rst#communication-establishment-between-sites-and-supervision-system). The site should respond with a MessageNotAck and close the connection. For the site to be able to send MessageNotAck the supervisor needs to wait until this message is received, and then close the connection.

**Comment by emiltin** [comment]
and if the site does not respons with a MessageNotAck, but sends e.g. Alarms?

**Comment by otterdahl** [comment]
I've added a suggestion the draft

**Comment by otterdahl** [comment]
I'm closing this. Feel free to open this issue again if you have any feedback on the draft
