### ISSUE TITLE
Message ACKs and communication establishment

### ISSUE THREAD

**Issue by Technolution-GGI** [rsmp-nordic/rsmp_core#4]
During integration of the RSMP interface between TLCs and city traffic management system (CTMS), we are facing the following situation and would appreciate your expertise to find a proper solution:

1. RSMP version exchange is performed successfully between TLC and CTMS
2. TLC and CTMS both send a watchdog command and receive the acknowledgment.
3. According to RSMP section 5.3.1, TLC starts sending aggregated status, alarms.
4. CTMS is acknowledging aggregated status, alarms received and also starts sending status unsubscribe/subscribe requests to the TLC.
5. As TLC is busy with points 3, it does not acknowledge the requests sent by CTMS (point 4) within a reasonable time span. After some time, CTMS dropped the connection.

We have been checking the RSMP specs, section 5.3.1, but we have not been able to conclude about what is incorrect in this situation. Nevertheless this situation is preventing establishing a connection.

**Comment by emiltin** [comment]
I'm not sure I like the proposal to only ignore missing ACKs, as long as something else is received.
If you're receiving other alarms, statuses, etc. it means that watchdogs are effectively disabled, as you cannot take any action if they're missing.

I think we should stick to the simle requirement that all messages must be ACK'ed within the time limit. Sites must then take care not to block the output with large number of messages, before sending the ACK.

**Comment by emiltin** [comment]
An issue with allowing acks not to be send in time if other messages are received is that this weaken the purpose of acks in any situation where many messages are exchanged, eg. when many status messages are send.

**Comment by emiltin** [comment]
If we leave the spec as it is, we need to instead speficy that messages send after reconnect is not strictly FIFO, acks must be interleaved.

**Comment by emiltin** [comment]
Working group decision is that we want to keep the requirement of receiving MessageAck within specified time limit. Instead we will update the specification to clarify that MessageAcks must be send within the limit, even when a large buffer of messages is being handled after a disconnect
.

**Comment by emiltin** [comment]
An alternativ would be to change the spec, so that you're not required to send watchdog regularly, but instead just ensure that something is send within a certain interval. If you have nothing to send, you send a watchdog.

**Comment by emiltin** [comment]
Watchdog currently have a secondary purpose, which is sending the time. But this is probably better handled in other ways.

**Comment by emiltin** [comment]
We're going for the simpler alternative described above. Draft needs to be updated.

**Comment by emiltin** [comment]
Proposal implies that it's an error to send a watchdog if something else has been send within the watchdog interval. Because if the site is busy sending buffered messages, it will not be able to acknowdledge to the wathdog.

**Comment by otterdahl** [comment]
Draft updated with e90a77a85d1226c3cc6c1e06b86330188c72ae7d.
However, it only cover watchdog messages. If, for instance StatusSubcribe is sent, then the same issue remains

**Comment by emiltin** [comment]
Going to move discussion about watchdogs to a separate issue, since it's not directly related to message acks.

**Comment by emiltin** [comment]
The draft and e90a77a actually implements #30. Is the below implemented in the spec?

> Working group decision is that we want to keep the requirement of receiving MessageAck within specified time limit. Instead we will update the specification to clarify that MessageAcks must be send within the limit, even when a large buffer of messages is being handled after a disconnect.

**Comment by otterdahl** [comment]
> The draft and e90a77a actually implements #30. Is the below implemented in the spec?

Yes. It was implemented with c6190f85e1bec18cce760040db922aef68eed7a3. Commit  e90a77a85d1226c3cc6c1e06b86330188c72ae7d actually implements #47.

I think this issue can be closed and is ready for review
