### ISSUE TITLE
Rework encryption

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#42]
RSMP includes optional support for SSL/TLS for encryption. It has come to my understanding that SSL/TLS is undesirable under certain circumstances and that a reworked encryption support is desired.

I suggest putting together a working group to work with the encryption support. This is a high priority issue for some and would preferably be included in the next release.

**Comment by rafaelcf2** [comment]
Hello David, agree you you.

**Comment by otterdahl** [comment]
With the introduction of encryption support in the RSMP simulator, this issue is no longer very urgent.

I suggest closing this issue for now. It can be reopened in the future if needed.
