### ISSUE TITLE
How and when is the rsmp version determined?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#43]
If both site and supervisor supports multiple version, and sends them in their Version messages when connecting, when and how is that actual rsmp version agreed?

site sends 3.1.1 and 3.1.2
supervisor responds with 3.1.2 and 3.1.3

what rsmp shuld be used and how do the site/supervisor determine it, and how do the site and supervisor agree on it?

**Comment by otterdahl** [comment]
In your example 3.1.2 is the latest supported version which both communicating parties supports, so this is the version which is used. In the chapter [RSMP/SXL Version](https://github.com/rsmp-nordic/rsmp_core/blob/master/rst/rsmp.rst#rsmpsxl-version) it is says: ```If both communicating systems support several RSMP versions it is always the latest version that should be used.```

All communication sent/recieved after the version message exchange uses the corresponding version.

**Comment by otterdahl** [comment]
This could be written more clearly in the specifcation

**Comment by emiltin** [comment]
so the site and the supervisor each looks at the versions and determines the latest version that both sides support, and assumes this is used?

after the supervisor determines 3.1.2 should be used, it then sends 3.1.2 and 3.1.3. that's the purpose of sending a version (3.1.3) that can never be used? wouldn't it be clearer to just send 3.1.2 and wait for the site to acknowledge this?

why does the supervisor send 3.1.3. when

**Comment by emiltin** [comment]
related to #38

**Comment by otterdahl** [comment]
I agree that it is not neccecary, but it can be useful to know from a debugging perspective. Perhaps someone uses the wrong version and no matching version can be found. It could be good to know which versions the supervisor supports.

**Comment by emiltin** [comment]
that makes sense.
but I miss a clear indication of what version is actually picked. If one side picks the wrong version, there is no way to tell from the communication.

**Comment by emiltin** [comment]
i think it would be good to add a field 'version_used' in the version message that the supervisor responds with. that would make it explicit what version is picked, and the site can acknowledge that.

**Comment by emiltin** [comment]
Working in supporting json validation of different rsmp core and sxl version, I noted that the rsmp gem was picking the latest version by sorting alphabetically. This works until for verison like "3.1.4" and "3.1.5", but breaks when you have e.g "1.0.9" and "1.0.10". The rsmp gem fixes this by using the Gem class which have helpers for comparing semantic versions string.
I think this examples supports the arugument for being explicit about what version is really used. Other rsmp implemantations could potentially have similar issues with picking the correct version. This would mean you end up with with two sides using different version without knowing it.

**Comment by emiltin** [comment]
Here's how the Gem class sorts version strings: https://github.com/rubygems/rubygems/blob/1aa8033952d4eda5ca131039822f9548166ab507/lib/rubygems/version.rb#L336-L361

**Comment by emiltin** [comment]
I should add that version negotiation only happens for the rsmp version. The sxl version is simply stated by the site, and the supervisor is expected to accept it. Not sure why it's designed this way.

**Comment by otterdahl** [comment]
I've added a suggestion the draft

**Comment by otterdahl** [comment]
I'm closing this. Feel free to open this issue again if you have any feedback on the draft
