### ISSUE TITLE
Use Github Pages instead of homebrew rst output

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#46]
I suggest using [Github Pages](https://pages.github.com/) instead of using a [homebrew script](https://github.com/rsmp-nordic/sxl-tools/blob/master/sphinx2rst.pl) to produce a readable version of the core specification on Github.

Using sphinx is useful since it can produce both HTML as well PDF as output, and at the same time being (almost) readable directly on Github.

Using Github Pages the core specification would look more [like this](https://otterdahl.org/rsmp/spec/) and be accessible at http://rsmp-nordic.github.io/rsmp_core.

The process involves using the `docs/` directory to host the HTML content of the site. The HTML content is produced with sphinx, which the specification is already written in.

The process for updating the specification is like this:
1. Edit the source rst file under `sphinx/source/`
2. Run the `sphinx2rst.pl`script in [sxl-tools](https://github.com/rsmp-nordic/sxl-tools) to update the `rst/`directory. The `rst/` directory contains the online view of the specification

I suggest changing step 2, to instead be like this:

2. Run `make html` to update the `docs/` directory. The `docs/` directory contains the content of the website at http://rsmp-nordic.github.io/rsmp_core.

Pros:
+ Using the HTML output produces a proper index and chapter numbers. This is not working well with the homebrew `sphinx2rst.pl` script.
+ Easier to read for non-technical users (not everybody likes to use the github interface)
+ Page still hosted at Github and each page has a **Edit on github** link

Cons:
- Only the master branch can be viewed. For older or draft versions we can only offer PDF:s or view the source at github

**Comment by emiltin** [comment]
Good idea. I like Github Pages.
It's a shame we can't show branches and older version of the spec as html as well, but maybe it's not so important. If we really want I guess we can output other branches to sub-folders for viewing with GitHub Pages.

**Comment by emiltin** [comment]
Let's do the same for SXL spec definations/appendixes

**Comment by otterdahl** [comment]
I've enabled Github pages, but it keep pointing to http://rsmp-nordic.org/rsmp_core instead of http://rsmp-nordic.github.io/rsmp_core. It doesn't seem that I can fix it using the Github interface. I guess I have to unarchive rsmp-nordic.github.io and remove the CNAME file, and then archive it again

**Comment by otterdahl** [comment]
I've removed the CNAME file of http://rsmp-nordic.github.io and added a HTML redirect instead.

**Comment by otterdahl** [comment]
I've switched to Github pages for the master branch (3.1.4) now. You can see it at https://rsmp-nordic.github.io/rsmp_core/. I've also updated https://rsmp-nordic.org/doks/ to link to https://rsmp-nordic.github.io/rsmp_core/ instead for the old rst page (only for 3.1.4)

**Comment by emiltin** [comment]
Great. I would use 'docs' instead of 'doks'.
BTW it seems there's an unfortunate mix og danish and english adresssen on our website:
https://rsmp-nordic.org/kontakt/
https://rsmp-nordic.org/news/ (hedder 'Om' i menuen...)

**Comment by emiltin** [comment]
Year the cname was from when I was hosting the entire site omn github pages. What's the redirect needed for?

**Comment by otterdahl** [comment]
The redirect is needed so that nobody by mistake would access https://rsmp-nordic.github.io/ and see the old web page

**Comment by emiltin** [comment]
You mean that GitHub still served the the old website with GitHub pages, even though the repo was archived?

**Comment by otterdahl** [comment]
Yes. But the CNAME file redirected to https://rsmp-nordic.org/, so it wasn't possible to see any contens

**Comment by emiltin** [comment]
Then I think we should turn off GitHub pages for the archived rsmp-nordic.github.io repo.

**Comment by otterdahl** [comment]
I can't find the option to turn GitHub pages off once the repo is archived. It seems a bit strange to me

**Comment by emiltin** [comment]
It's a bit odd. Seems other people are having problems disabling gh-pages:
https://github.community/t5/GitHub-Pages/Can-not-disable-gh-pages-even-after-the-gh-pages-branch-has-been/td-p/25393

It's try renaming the master branch.
https://help.github.com/en/github/working-with-github-pages/unpublishing-a-github-pages-site

**Comment by emiltin** [comment]
I've renamed the master branch to master-archived. This disabled gh-pages and https://rsmp-nordic.github.io/ now just returns a 404. There's no need for the redirect, but I'll just leave it.

I've archived the repo again.

**Comment by otterdahl** [comment]
Fixed
