### ISSUE TITLE
syntax highlight JSON examples in sphinx documentation

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#49]
Can we enable syntax highlighting for JSON example like these?
https://rsmp-nordic.github.io/rsmp_core/applicability/transport_of_data.html#wrapping-of-packets

Should be possible:
https://www.sphinx-doc.org/en/1.5/markup/code.html
https://stackoverflow.com/questions/4259105/which-sphinx-code-block-language-to-use-for-json

This also applies to SXL docs.

**Comment by emiltin** [comment]
Hm.. Seems by coincidence I looked at the only example which is invalid JSON and is therefore not highlighted? Other examples do highlighting, although because numbers are send as strings, the highlighting looks a bit bland.

**Comment by otterdahl** [comment]
That example doesn't work because it is not valid JSON since it contains `<0x0c>` which is used for the wrapping of JSON packets

**Comment by emiltin** [comment]
right
