### ISSUE TITLE
Order of ACK for version messages and aggregated status message

### ISSUE THREAD

**Issue by MarcoRijshouwer** [rsmp-nordic/rsmp_core#5]
During the integration test between CTMS and a Swarco TLC we saw some behavior which we found odd. We saw the next exchange of messages:
TLC -> CTMS: Version message
CTMS -> TLC: Ack
CTMS -> TLC: Version message
TLC -> CTMS: Aggregated status

CTMS expected the TLC to send an acknowledgement on the version message before it sends an aggregated status message. Is it allowed to send the aggregated status message before all version messages including acknowledgements are sent?

**Comment by emiltin** [comment]
resolved.
