### ISSUE TITLE
Is it allowed to switch interval time by sending new subscription request?

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#52]
Is it allowed to switch interval time by sending new subscription request while the subscription is already active?

**Comment by emiltin** [comment]
You could argue that it's not much different from unsubscribing and subscribing with a new interval. I would allow it.

**Comment by otterdahl** [comment]
I'm closing this. Feel free to open this issue again if you have any feedback on the draft
