### ISSUE TITLE
Consider letting uRt=0 mean update on change=true

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_core#56]
In earlier versions of RSMP (<3.1.5) **uRt: 0** meant to send update on change. In RSMP 3.1.5 this feature is enabled using **sOc: true** instead. To prevent the ability to send confusing combinations, e.g:

```
             "uRt": "0",
             "sOc": false
```
The decision was made to simply let **uRt:0** no longer mean **update on change**. It no longer means anything specific, only that update on interval is not enabled. The above example now means that no updates to the subscription request will be sent at all. 
(Perhaps this can be clarified better in [the specification](https://rsmp-nordic.github.io/rsmp_core/applicability/basic_structure.html?highlight=updaterate#structure-for-a-status-subscription-request-message-on-one-or-several-objects)?)

After some thoughts about this, I see good reasons not to allow the above example to mean **update on change=true** for backwards compatibility, even though **"sOc": false**.

**Comment by emiltin** [comment]
I assume you can leave out sOc, so we are backwardd compatible?

Can you leave out uRt, if sOc=true?

Is uRt=0 and sOc=false allowed, and if so what is the expected behavior?

This formulation regaring uRt is unclear to me: If “0” it means that the value should not be sent according to an interval. So it should not be send regularly, but should it be send when it changes?

**Comment by otterdahl** [comment]
> This formulation regaring uRt is unclear to me: _If “0” it means that the value should not be sent according to an interval._ So it should not be send regularly, but should it be send when it changes?

It just means that updateRate is disabled. If you'd like to have updates on change you needs to set sOc: true

**Comment by emiltin** [comment]
I don't think we should allow uRt=0 and sOc=false, since it would mean you never get any subscriptions. I tihnk it's confusing, and don't see a use for it?

**Comment by otterdahl** [comment]
> I don't think we should allow uRt=0 and sOc=false, since it would mean you never get any subscriptions. I tihnk it's confusing, and don't see a use for it?

Sure, we can add a clarification that this combination is invalid.
