### ISSUE TITLE
Invalid security code and NotAck

### ISSUE THREAD

**Issue by MarcoRijshouwer** [rsmp-nordic/rsmp_core#79]
During the integration test between CTMS and a Swarco TLC we sent an invalid security code in a command message. We expected to receive a NACK from the TLC, but the TLC did not reply on the command message. Should a TLC send a NACK or not? What is the correct behavior and is it documented?

**Comment by otterdahl** [comment]
Since this change (as stated above) would mean a slightly different behaviour of CommandReponse and MessageAck than stated in core.  This needs to be stated in the SXL instead for all commands where security code is used.

**Comment by otterdahl** [comment]
Clarification has been added to all commands in the TLC SXL which uses security code. 
See e.g. http://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1-draft/sxl_traffic_light_controller.html#m0001

**Comment by emiltin** [comment]
done
