### ISSUE TITLE
SecurityCode: unique per supervision system or tlc?

### ISSUE THREAD

**Issue by alexanderzapf** [rsmp-nordic/rsmp_core#85]
We were wondering if the security code is meant to be specified per connection/supervision system or tlc. How is this normally handled in a multi supervision system topology?
And is there is a common or "official" default value for them?

**Comment by otterdahl** [comment]
Yes, I think it's global.

**Comment by emiltin** [comment]
hi @alexanderzapf did this answer your question?

**Comment by alexanderzapf** [comment]
Hi @emiltin yes it did, thank you!
