### ISSUE TITLE
4.4.4.3 diagram should mention sendOnChang

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#93]
the diagram at https://rsmp-nordic.org/rsmp_specifications/core/3.1.5/applicability/basic_structure.html#message-exchange-between-site-and-supervision-system-other-equipment-subscription

states that a statusupdate is send when "status is changed (uRt=0) or interval time reached". i think this should be updated to reflect the new sendOnChange flag.

**Comment by otterdahl** [comment]
Well spotted. Diagram updated with commit 489d8475a9a1bd8fb3b4161f3737c3f3c51ff963

**Comment by emiltin** [comment]
done
