### ISSUE TITLE
example of alarm suspended message uses incorrect casing

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_core#95]
in https://rsmp-nordic.org/rsmp_specifications/core/3.1.5/applicability/basic_structure.html#structure-for-alarm-suspend-message, "JSon code 8: Response of alarm suspend message", includes

```json
     "sS": "Suspended",
```

but according to https://rsmp-nordic.org/rsmp_specifications/core/3.1.5/applicability/basic_structure.html#alarm-status, allowed values include "suspended" and "notSuspended".

**Comment by otterdahl** [comment]
Well spotted. Fixed in 534ec99619f2e5e165731a6894f4c49f95f9cdbb

**Comment by emiltin** [comment]
done
