### ISSUE TITLE
Recommend way to share timeouts and intervals between the Supervisor and the Site

### ISSUE THREAD

**Issue by melihercan** [rsmp-nordic/rsmp_core#97]
Spec 3.1.5. states the following on Watchdog section:

`The interval duration for sending watchdog messages should be configurable at both the site and the
supervision system. The default setting should be (1) once a minute.`

That implies to me that there should be a way to convey Watchdog interval from Supervisor to the site. I couldn't find anything regarding how to perform this in the spec. 

Ideally both sides should use the same interval otherwise one end may end up with Watchdog timeout for example.

This raises a general question: 
What is the recommended way to share these kind of timeouts and intervals between the Supervisor and  the Site? A shared file (YAML or JSON) seems to be the straightforward solution but it is static and requires reboots when changed. 
Any other suggestions?

**Comment by emiltin** [comment]
Hi,
There is no build-in RSMP method for sharing this kind of information between sites and supervisors.

There are other things that must have matching configurations on sites and supervisor, like component ids. Making this smarter is on the roadmap, see e.g. #13 for one example.

Sharing config data manaually between sites and supervisor can really be done any way you find convenient. Usually there is no need to share files, all you do is manually edit config files on both sites to match e.g. watchdog interval and timeout.

**Comment by melihercan** [comment]
Thanks for the feedback Erin.
